name: Build and Release on Main

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'
  workflow_dispatch:

jobs:
  build-and-release:
    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-latest, windows-latest]
        include:
          - platform: ubuntu-latest
            rust_target: x86_64-unknown-linux-gnu
          - platform: windows-latest
            rust_target: x86_64-pc-windows-msvc

    runs-on: ${{ matrix.platform }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'

      - name: Install Rust
        uses: dtolnay/rust-toolchain@1.82.0
        with:
          targets: ${{ matrix.rust_target }}

      - name: Install Linux dependencies
        if: matrix.platform == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libgtk-3-dev \
            libwebkit2gtk-4.1 \
            libwebkit2gtk-4.1-dev \
            libayatana-appindicator3-dev \
            librsvg2-dev \
            patchelf \
            libsoup-3.0-dev \
            pkg-config \
            libssl-dev \
            libxdo-dev

      # Windows-specific system dependencies not required with current crate set
      # (gtk is linux-only via Cargo.toml target filters)

      - name: Install app dependencies
        run: npm ci

      - name: Update Rust dependencies
        run: |
          cd src-tauri
          cargo update
          cargo update time --precise 0.3.36

      - name: Build web assets
        run: npm run build

      - name: Rust build (non-main branches)
        if: github.ref != 'refs/heads/main'
        run: |
          cd src-tauri
          cargo build --release --locked

      - name: Generate version and tag
        id: version
        if: github.ref == 'refs/heads/main' && matrix.platform == 'ubuntu-latest'
        run: |
          latest_tag=$(git describe --tags --abbrev=0 2>/dev/null || echo "v0.0.0")
          echo "Latest tag: $latest_tag"
          version_parts=(${latest_tag//./ })
          major=${version_parts[0]#v}
          minor=${version_parts[1]}
          patch=${version_parts[2]}
          new_patch=$((patch + 1))
          new_version="v${major}.${minor}.${new_patch}"
          echo "New version: $new_version"
          echo "version=$new_version" >> $GITHUB_OUTPUT
          echo "tag_name=$new_version" >> $GITHUB_OUTPUT

      - name: Build Tauri app (Release on main)
        if: github.ref == 'refs/heads/main'
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAURI_PRIVATE_KEY: ${{ secrets.TAURI_PRIVATE_KEY }}
          TAURI_KEY_PASSWORD: ${{ secrets.TAURI_KEY_PASSWORD }}
        with:
          args: --config src-tauri/tauri.conf.json
          distPath: ../dist/konductor
          iconPath: src-tauri/icons/icon.png
          tagName: ${{ steps.version.outputs.tag_name }}
          releaseName: "[Unaffiliated] ${{ steps.version.outputs.version }}"
          releaseBody: |
            ## Release ${{ steps.version.outputs.version }}

            ### Changes in this release:
            - Auto-generated release from main branch merge
            - Built for ${{ matrix.platform }}

            See the assets to download this version and install.
          releaseDraft: false
          prerelease: false

      - name: Upload artifacts (Release only)
        if: github.ref == 'refs/heads/main'
        uses: actions/upload-artifact@v4
        with:
          name: konductor-${{ matrix.platform }}-${{ steps.version.outputs.version }}
          path: |
            src-tauri/target/release/bundle/

      - name: Create Release Summary
        if: github.ref == 'refs/heads/main' && matrix.platform == 'ubuntu-latest' && success()
        run: |
          echo "✅ Release ${{ steps.version.outputs.version }} built successfully!" > release-notes.txt
          echo "Platform: ${{ matrix.platform }}" >> release-notes.txt
          echo "Check the release page for download links." >> release-notes.txt
