name: Konductor Builder

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  release:
    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-latest, windows-latest]   # Add ubuntu-latest here
        include:
          - os: ubuntu-latest
            rust_target: x86_64-unknown-linux-gnu
          - os: windows-latest
            rust_target: x86_64-pc-windows-msvc
          # You can keep macOS if you want:
          # - os: macos-latest
          #   rust_target: x86_64-apple-darwin
          # - os: macos-latest
          #   rust_target: aarch64-apple-darwin

    runs-on: ${{ matrix.platform }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build Changelog
        id: build_changelog
        run: echo "changelog=- ADD CHANGELOG" >> $GITHUB_OUTPUT

      - name: Node.js setup
        uses: actions/setup-node@v3
        with:
          node-version: latest

      - name: Install Rust (Stable)
        run: curl https://sh.rustup.rs -sSf | sh -s -- -y

      - name: Install dependencies (ubuntu only)
        if: matrix.platform == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev webkit2gtk-4.0 libappindicator3-dev librsvg2-dev patchelf

      - name: Install app dependencies and build web
        run: npm install && npm run build

      - name: Build the app with tauri-action
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAURI_PRIVATE_KEY: ${{ secrets.TAURI_PRIVATE_KEY }}
          TAURI_KEY_PASSWORD: ${{ secrets.TAURI_KEY_PASSWORD }}
        with:
          tagName: ${{ github.ref_name }}
          releaseName: "[Unaffiliated] v__VERSION__"
          releaseBody: |
            ${{ steps.build_changelog.outputs.changelog }}
            See the assets to download this version and install.
          releaseDraft: true
          prerelease: false

      - name: Update README with new version and download link
        if: success()
        run: |
          # Build direct download URLs for both platforms
          echo "- **${{ github.ref_name }} (Windows):** [Download Latest Version](https://github.com/Manukhurana97/konductor/releases/download/${{ github.ref_name }}/your-app-windows.zip)" > README.md
          echo "- **${{ github.ref_name }} (Linux):** [Download Latest Version](https://github.com/Manukhurana97/konductor/releases/download/${{ github.ref_name }}/your-app-linux.AppImage)" >> README.md