name: Konductor Builder

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  release:
    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-22.04, windows-latest]
        include:
          - platform: ubuntu-22.04
            rust_target: x86_64-unknown-linux-gnu
          - platform: windows-latest
            rust_target: x86_64-pc-windows-msvc

    runs-on: ${{ matrix.platform }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build Changelog
        id: build_changelog
        run: echo "changelog=- ADD CHANGELOG" >> $GITHUB_OUTPUT

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: 1.80.0
          targets: ${{ matrix.rust_target }}

      - name: Install Linux dependencies
        if: matrix.platform == 'ubuntu-22.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libwebkit2gtk-4.0-dev \
            build-essential \
            curl \
            wget \
            libssl-dev \
            libgtk-3-dev \
            libayatana-appindicator3-dev \
            librsvg2-dev

      - name: Install app dependencies and build web
        run: npm ci && npm run build

      - name: Build the app with Tauri
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAURI_PRIVATE_KEY: ${{ secrets.TAURI_PRIVATE_KEY }}
          TAURI_KEY_PASSWORD: ${{ secrets.TAURI_KEY_PASSWORD }}
        with:
          tagName: ${{ github.ref_name }}
          releaseName: "[Unaffiliated] v__VERSION__"
          releaseBody: |
            ${{ steps.build_changelog.outputs.changelog }}
            See the assets to download this version and install.
          releaseDraft: true
          prerelease: false

      - name: Update README with new version and download link
        if: success()
        run: |
          echo "- **${{ github.ref_name }} (Windows):** [Download Latest Version](https://github.com/Manukhurana97/konductor/releases/download/${{ github.ref_name }}/your-app-windows.zip)" > README.md
          echo "- **${{ github.ref_name }} (Linux):** [Download Latest Version](https://github.com/Manukhurana97/konductor/releases/download/${{ github.ref_name }}/your-app-linux.AppImage)" >> README.md
